config/routes.rb
Rails.application.routes.draw do
  # mount Rswag::Api::Engine => '/api-docs'
  # mount Rswag::Ui::Engine => '/api-docs'
  # mount ActionCable::server => '/cable'


  resources :employees, only: %i[new create], path: 'funcionarios'
  resource :two_factor_settings#, except: [:index, :show]

  # Auth
  devise_for :admin, controllers: {
    password_expired: 'funcionarios/password_expired',
    sessions: 'admin/sessions',
  }

  devise_for :empresas, controllers: {
    registrations: 'empresas/registrations',
    password_expired: 'funcionarios/password_expired',
    sessions: 'empresas/sessions',
  }

  devise_for :funcionarios, controllers: {
    omniauth_callbacks: 'funcionarios/omniauth_callbacks',
    registrations: 'funcionarios/registrations',
    sessions: 'funcionarios/sessions',
    password_expired: 'funcionarios/password_expired',
  }

  devise_for :consultants, controllers: {
    registrations: 'consultants/registrations',
    password_expired: 'funcionarios/password_expired',
    sessions: 'consultants/sessions',
  }

  devise_for :consultant_teams, controllers: {
    registrations: 'consultant_teams/registrations',
    password_expired: 'funcionarios/password_expired',
    sessions: 'consultant_teams/sessions',
  }

  # Pages
  get 'consultant', to: 'pages#consultant'
  get 'contact', to: 'pages#contact'
  root to: 'pages#home'
  get 'lgpd_text', to: 'pages#lgpd_text'

  resource :dashboard, only: :show

  # Resources
  resources :tutorials, path: 'tutoriais', only: :index

  resources :empresas_pages do
    collection do
      get :importar_funcionarios
      post :importar_funcionarios_create
    end
  end

  get 'empresas/:id/funcionarios', to: 'companies#employees', as: :company_employees

  get 'funcionarios_form/:id', to: 'empresas_pages#funcionarios_form', as: :funcionarios_form
  patch 'funcionarios_form/:id', to: 'empresas_pages#funcionarios_form_update', as: :funcionarios_form_update
  get 'funcionarios_function', to: 'empresas_pages#funcionarios_function', as: :funcionarios_function

  patch 'toggle_empregador/:id', to: 'empresas_pages#toggle_empregador', as: :toggle_empregador
  patch 'toggle_gestor/:id', to: 'empresas_pages#toggle_gestor', as: :toggle_gestor

  get 'consultants_outsourcing', to: 'consultants_pages#consultants_outsourcing', as: :consultants_outsourcing
  put 'habilitar_consultor/:consultant_id/:company_id', to: 'consultants_pages#enable_company', as: :habilitar_consultor

  resources :funcionarios_pages do
    collection do
      get :importar_funcionarios
      post :importar_funcionarios_create
    end
  end

  get 'vinculos_form/:id', to: 'funcionarios_pages#vinculos_form', as: :vinculos_form
  patch 'vinculos_form/:id', to: 'funcionarios_pages#vinculos_form_update', as: :vinculos_form_update
  patch 'desativar_vinculo', to: 'funcionarios_pages#desativar_vinculo', as: :desativar_vinculo

  get 'destroy_funcionario/:id', to: 'funcionarios_pages#destroy_funcionario', as: :destroy_funcionario

  resources :atestados

  get '/atestados_funcionario/:id', to: 'atestados#atestados_funcionario', as: :atestados_funcionario

  resources :okays, only: %i[index]

  post '/empresa_okay/:id', to: 'atestados#empresa_okay', as: :empresa_okay
  post '/funcionario_okay/:id', to: 'atestados#funcionario_okay', as: :funcionario_okay
  post '/empresa_subscrever/:id', to: 'atestados#empresa_subscrever', as: :empresa_subscrever
  post '/empresa_reverter/:id', to: 'atestados#empresa_reverter', as: :empresa_reverter

  resources :cfms, only: %i[new create]
  resources :importar_funcionarios, only: %i[index create]
  resources :bi_urls, only: %i[new create]

  get 'aceitar_lgpd', to: 'funcionarios_pages#show_lgpd'
  post 'update_lgpd', to: 'funcionarios_pages#update_lgpd'

  resources :password_resets

  get 'cid/buscar', to: 'cids#search', as: :cid_search

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :atestados, only: %i[index show]
      resources :funcionarios, only: %i[create]
      get 'opt', to: 'checks#verify_opt'
      get 'send_code', to: 'checks#send_email_with_code'
      post 'verify_code', to: 'checks#verify_code'
    end
  end

  resources :consultants, only: :index

  resources :collaborators, only: :index, path: 'colaboradores' do
    member do
      patch :authorize, path: 'autorizar'
      patch :revoke, path: 'revogar'
    end
  end

  get 'funcionarios_empresa', to: 'funcionarios_pages#funcionarios_empresa', as: 'funcionarios_empresa'

  get 'funcionarios_por_empresa/:id', to: 'atestados#funcionarios_por_empresa'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  # mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?

  resources :squads do
    collection do
      get :list
    end
  end
end

app/controllers/funcionarios_pages_controller.rb
class FuncionariosPagesController < ApplicationController
  include AccountScope
  include BondFiltersConcern

  require_any_except! roles: %i[company], only: %i[index funcionarios_empresa]
  require_any_except! roles: %i[company], only: %i[vinculos_form vinculos_form_update]
  require_admin! only: %i[destroy_funcionario]
  require_employee! only: %i[show_lgpd update_lgpd]

  layout 'redesign', only: %i[index show_lgpd vinculos_form vinculos_form_update importar_funcionarios]

  FILTERS = {
    roles: %i[employee manager employer],
    user_statuses: %i[active inactive]
  }

  def index
    if admin?
      @vinculos = Vinculo.all
      @empresas = Empresa.all

      authorized_company_ids = @empresas.ids
    elsif employee? && current_user.employer?
      authorized_company_ids = Funcionario.employer_company_ids(current_user)

      @vinculos = Vinculo.where(empresa_id: authorized_company_ids)
    elsif consultant?
      authorized_company_ids = current_consultant.authorized_company_ids

      @empresas = Empresa.where(id: authorized_company_ids)
    elsif collaborator?
      authorized_company_ids = current_consultant_team.authorized_company_ids

      @empresas = Empresa.where(id: authorized_company_ids)
    else
      redirect_to root_path
    end

    @departments = departments_for(authorized_company_ids)

    if params[:company_id].present?
      @departments = departments_for(params[:company_id])
    end
    @job_functions = job_functions_for(authorized_company_ids)
  end

  def funcionarios_empresa
    if admin?
      @vinculos = Vinculo.all
    elsif consultant? || collaborator?
      authorized_company_ids = current_user.authorized_company_ids

      @vinculos = Vinculo.where(empresa_id: authorized_company_ids)

      params[:empresa_id] = nil unless authorized_company_ids.include? params[:empresa_id].to_i
    elsif employee? && current_user.employer?
      bond = current_user.most_recent_bond

      @vinculos = Vinculo.where(empresa_id: bond.empresa_id)
    else
      return render_not_found_page
    end

    @vinculos = @vinculos.includes(:funcionario)

    @vinculos = @vinculos.where(empresa_id: params[:empresa_id]) if params[:empresa_id].present?

    @vinculos = @vinculos.global_search(params[:query]) if params[:query].present?

    @vinculos = filter_by_role(@vinculos, params[:role].to_sym) if params[:role].present?

    @vinculos = filter_by_status(@vinculos, params[:user_status].to_sym) if params[:user_status].present?

    @vinculos = filter_by_department(@vinculos, params[:department]) if params[:department].present?
    @vinculos = filter_by_job_function(@vinculos, params[:job_function]) if params[:job_function].present?

    @vinculos = filter_by_employee_leader(@vinculos, params[:funcionario_lider_id]) if params[:funcionario_lider_id].present?

    @vinculos = @vinculos.left_joins(:refatestados)
                         .group(:id)
                         .reorder('COUNT("atestados"."id") DESC')


    respond_to do |format|
      format.html { render layout: false }
      format.json { render json: { funcionarios: @funcionarios } }
    end
  end

  def vinculos_form
    return render_not_found_page if employee? && !current_user.employer?

    bond_scope = Vinculo.where(funcionario_id: params[:id])

    if consultant? || collaborator?
      authorized_company_ids = current_user.authorized_company_ids

      bond_scope = bond_scope.where(empresa_id: authorized_company_ids)
    elsif employee? && current_user.employer?
      company_id = current_user.most_recent_bond.empresa_id
      bond_scope = bond_scope.where(empresa_id: company_id)
    end

    if bond_scope.exists?
      @funcionario = bond_scope.first.funcionario
    else
      render_not_found_page
    end
  end

  def vinculos_form_update
    return render_not_found_page if employee? && !current_user.employer?

    bond_scope = Vinculo.where(funcionario_id: params[:id])

    if consultant? || collaborator?
      authorized_company_ids = current_user.authorized_company_ids

      bond_scope = bond_scope.where(empresa_id: authorized_company_ids)
    elsif employee? && current_user.employer?
      company_id = current_user.most_recent_bond.empresa_id
      bond_scope = bond_scope.where(empresa_id: company_id)
    end

    if bond_scope.exists?
      employee = bond_scope.first.funcionario

      if employee.update!(funcionario_params)
        redirect_to funcionarios_pages_path, notice: 'Funcionário(a) atualizado com sucesso!'
      end
    else
      render_not_found_page
    end
  end

  def show_lgpd; end

  def update_lgpd
    current_user.update!(
      funcionario_lgpd: true
    )

    redirect_to new_atestado_path
  end

  def destroy_funcionario
    employee = Funcionario.find_by_id(params[:id])

    message = t('.error')

    message = t('.success') if employee && employee.destroy(:hard)

    redirect_to funcionarios_pages_path, notice: message
  end

  def desativar_vinculo
    redirect_to root_path unless employee?

    employee = Funcionario.find(current_user.id)
    current_vinculo = employee.most_recent_bond
    current_vinculo.ativo = false
    current_vinculo.empregador = false
    current_vinculo.gestor = false
    current_vinculo.save

    redirect_to root_path
  end

  def importar_funcionarios
    set_empresa
  end

  def importar_funcionarios_create
    return redirect_to funcionarios_pages_path, notice: "Favor Selecione um arquivo CSV!" if params[:employee][:file].nil?
    empresa_id = params[:employee][:empresa_id].nil? ?  current_user.empresa.id : params[:employee][:empresa_id]

    xlsx = Roo::Spreadsheet.open(params[:employee][:file].tempfile)
    xlsx.each_with_index do |row, index|
      next if index.zero?

      begin
        funcionario = Funcionario.find_or_create_by(cpf: row[1])
        password = SecureRandom.hex(10)
        
        funcionario.update!({
          nome: row[0],
          rg: row[2],
          data_nascimento: row[3].strftime('%d/%m/%Y'),
          sexo: row[4],
          celular: row[5],
          email: row[6],
          registro_empresa: row[10],
          pis: row[11],
          risco_ocupacional: row[12],
          password: password,
          password_confirmation: password
        })
       
        squad = Squad.find_or_create_by(
          name: row[8], 
          empresa: Empresa.find(empresa_id)
        )

        vinculo = Vinculo.find_or_create_by(
          empresa_id: empresa_id,
          funcionario_id: funcionario.id,
        )
        vinculo.update({
          empregador: false,
          cargo:  row[7],
          squad: squad,
          aprovado: false,
          cnpj_employee:  row[9],
          ativo: (row[13].to_s.downcase == "ativo")? true: false
        })
      rescue
      end
    end

    return redirect_to funcionarios_pages_path, notice: "Processamos o arquivo com sucesso!" if consultant? || collaborator?
    redirect_to empresas_pages_path, notice: "Processamos o arquivo com sucesso!"
  end

  private

  def funcionario_params
    params.require(:funcionario).permit(
      :cargo, :registro_empresa,
      :pis, :risco_ocupacional,
      :nome,
      vinculos_attributes: %i[
        ativo
        squad_id cargo
        cnpj_employee
        id
        funcionario_lider_id
        cargo
      ]
    )
  end

  def filter_by_role(bonds, role)
    return bonds if bonds.empty? || !FILTERS[:roles].include?(role)

    case role
    when :employee
      bonds.where(empregador: false, gestor: false)
    when :manager
      bonds.where(empregador: false, gestor: true)
    when :employer
      bonds.where(empregador: true, gestor: false)
    else
      bonds
    end
  end

  def filter_by_status(bonds, status)
    return bonds if bonds.empty? || !FILTERS[:user_statuses].include?(status.to_sym)

    filtered_bonds = bonds.joins('INNER JOIN funcionarios AS func ON vinculos.funcionario_id = func.id')

    case status.to_sym
    when :active
      filtered_bonds.where('vinculos.ativo = true')
    when :inactive
      filtered_bonds.where('vinculos.ativo = false')
    else
      filtered_bonds
    end
  end

  def set_empresa
    if admin?
      @vinculos = Vinculo.all
      @empresas = Empresa.all

      authorized_company_ids = @empresas.ids
    elsif employee? && current_user.employer?
      authorized_company_ids = Funcionario.employer_company_ids(current_user)

      @vinculos = Vinculo.where(empresa_id: authorized_company_ids)
    elsif consultant?
      authorized_company_ids = current_consultant.authorized_company_ids

      @empresas = Empresa.where(id: authorized_company_ids)
    elsif collaborator?
      authorized_company_ids = current_consultant_team.authorized_company_ids

      @empresas = Empresa.where(id: authorized_company_ids)
    end
  end

end

app/views/funcionarios_pages/_filters.html.erb
<%= render 'redesign/shared/modal' do %>
  <h3>Filtros</h3>

  <%= simple_form_for('', url: funcionarios_empresa_path, method: :get,
    html: { class: 'gray-form', id: 'filterForm' },
    defaults: {
      wrapper_html: { class: 'default-wrapper-form' },
      input_html: { class: 'custom-input' }
    }) do |f| %>

    <%= f.input :query, as: :hidden, input_html: { value: params[:query] } %>

    <div class="flex flex-col gap-4">
      <% unless employee? && current_user.employer? %>
        <%= f.input :empresa_id,
          collection: @empresas,
          label: 'Empresa',
          label_method: :razao_social,
          value_method: :id,
          include_blank: true,
          input_html: {
            class: 'js-select simple-select',
            id: 'filterFormCompanyId',
            onchange: 'triggerForm()'
          },
          selected: params[:empresa_id],
          prompt: 'Selecione uma empresa',
          required: false %>
      <% end %>

      <%= f.input :role,
        collection: [
          ['Empregador', 'employer'],
          ['Gestor', 'manager'],
          ['Funcionário', 'employee']
        ],
        selected: params[:role],
        prompt: 'Selecione um perfil',
        input_html: {
          id: 'filterFormRole',
          class: 'js-select'
        },
        include_blank: true,
        required: false %>

      <%= f.input :user_status,
        collection: [
          ['Ativo', 'active'],
          ['Inativo', 'inactive']
        ],
        selected: params[:user_status],
        prompt: 'Selecione um status',
        input_html: {
          id: 'filterFormUserStatus',
          class: 'js-select'
        },
        include_blank: true,
        required: false %>

      <%= f.input :department,
        collection: squads_by_user,
        selected: params[:department],
        prompt: 'Selecione o Departamento',
        input_html: {
          id: 'filterFormDepartment',
          class: 'js-select'
        },
        include_blank: true,
        required: false %>

      <%= f.input :job_function,
        collection: @job_functions,
        selected: params[:job_function],
        prompt: 'Selecione o Cargo',
        input_html: {
          id: 'filterFormJobFunction',
          class: 'js-select'
        },
        include_blank: true,
        required: false %>

      <%= f.input :funcionario_lider_id,
          collection: lideres_by_empresa,
          selected: params[:funcionario_lider_id],
          prompt: 'Selecione o Lider Direto',
          input_html: { class: 'js-select' },
          include_blank: true,
          required: false %>

      <div class="filters-form">
        <div class="flex flex-row flex-wrap gap-4 mt-4">
          <%= link_to 'Limpar Filtros', funcionarios_pages_path, class: 'clear-filters-button' %>

          <%= f.button :submit, 'Filtrar', class: 'filter-button button', data: { disable_with: false } %>
        </div>
      </div>
    </div>
  <% end %>

  <script>
    $(document).ready(function(event) {
      const filterForm = $("#filterForm");
      const filterButton = $(".filter-button");

      const closeModalButton = $(".close-modal");

      filterForm.on('submit', function() {
        closeModalButton.trigger("click");
      });

      filterButton.on('click', function() {
        closeModalButton.trigger("click");
      });
    });

    function triggerForm() {
      $('#filterForm').submit();

      let company_id = $('#filterFormCompanyId').val();

      console.log('Listando squads')
      $.ajax({
        url: `/squads/list?company_id=${company_id}`,
        method: 'get',
        dataType: 'json',
        success: function(jsonData) {
          var selectElement = $('#filterFormDepartment');
          selectElement.empty();

          selectElement.append($('<option>', {
            value: '',
            text: 'Selecione o Departamento'
          }));

          selectElement.append($('<option>', {
            value: '',
            text: ''
          }));

          $.each(jsonData, function(index, item) {
            selectElement.append($('<option>', {
                value: item.id,
                text: item.name
            }));
        });

          selectElement.selectpicker('destroy');
          selectElement.selectpicker({
            liveSearch: true,
            liveSearchNormalize: true,
            liveSearchPlaceholder: "Buscar",
            style: null,
            noneSelectedText: "Nenhuma opção selecionada",
            noneResultsText: "Nenhum resultado encontrado",
            selectAllText: "Selecionar todos",
            container: "body",
          });
        },
      });
    }
  </script>
<% end %>

app/views/funcionarios_pages/edit.html.erb
<h1>Editing Funcionario</h1>

<%= render 'form', funcionario: @funcionario %>

<%= link_to 'Show', @funcionario %> |
<%= link_to 'Back', funcionarios_pages_path %>

app/views/funcionarios_pages/funcionarios_empresa.html.erb
<% if @vinculos.length > 0 %>
  <h3 class="text-lg mt-5 mb-3">
    Total de Funcionários: <%= @vinculos.length %>
  </h3>
<% end %>

<table class="custom-table">
  <thead>
    <tr>
      <th role="col" class="text-center">Nome</th>
      <th role="col" class="hidden md:table-cell text-center">E-mail</th>
      <th role="col" class="hidden md:table-cell text-center">Departamento</th>
      <th role="col" class="text-center">Cargo</th>
      <th role="col" class="hidden md:table-cell text-center">Líder Direto</th>
      <th role="col" class="hidden md:table-cell text-center">Status Usuário</th>
      <th role="col" class="hidden md:table-cell text-center">Perfil</th>
      <th role="col" class="text-center">Qtd. Atestados</th>
      <th role="col" class="text-center">Ações</th>
    </tr>

    <tbody>
      <%- if @vinculos.length > 0 %>
        <% @vinculos&.each do |vinculo| %>
          <tr>
            <td>
              <%= vinculo.funcionario.nome %>
            </td>

            <td class="hidden md:table-cell">
              <%= vinculo.funcionario.email %>
            </td>

            <td class="hidden md:table-cell">
              <%= vinculo.squad %>
            </td>

            <td class="text-center">
              <%= vinculo.cargo %>
            </td>

            <td class="hidden md:table-cell">
              <%= vinculo.nome_lider %>
            </td>

            <td class="hidden md:table-cell">
              <% if vinculo.ativo %>
                <span class="tag active">Ativo</span>
              <% else %>
                <span class="tag deactivated">Inativo</span>
              <% end %>
            </td>

            <td class="text-center hidden md:table-cell">
              <%= t(role_by_bound(vinculo), scope: 'empresas_pages.index.roles') %>
            </td>

            <td class="text-center">
              <div class="flex items-center justify-center">
                <%= vinculo.refatestados.where(empresa_id: current_user.authorized_company_ids).count %>
                <%= inline_svg 'icons/alert', style: "width: 20px; height: 20px; margin-left: 10px" if vinculo.sum_tempo_de_dispensa_em_horas_per_funcionario? %>
              </div>
            </td>

            <td class="relative">
              <button aria-haspopup="true" aria-expanded="false" class="action dropdown-button">
                <%= inline_svg 'icons/ellipsis', alt: 'Ações', class: 'mx-auto' %>
              </button>

              <ul class="custom-dropdown-menu hidden" aria-labelledby="dropdown-button" role="menu">
                <li role="menuitem">
                  <%= link_to t('.actions.edit'), vinculos_form_path(vinculo.funcionario_id), class: 'edit-info' %>
                </li>

                <% if company? || (employee? && current_user.employer?) %>
                  <li role="menuitem">
                    <%= link_to "#{vinculo.gestor ? 'Remover atribuição de gestor' : 'Atribuir como gestor'}", toggle_gestor_path(vinculo), method: :patch %>
                  </li>
                <% end %>

                <% if consultant? || collaborator? %>
                  <li role="menuitem">
                    <%= link_to "#{vinculo.empregador ? 'Remover empregador' : 'Adicionar empregador'}", toggle_empregador_path(vinculo), method: :patch %>
                  </li>

                  <li role="menuitem">
                    <%= link_to "#{vinculo.gestor ? 'Remover gestor' : 'Adicionar gestor'}", toggle_gestor_path(vinculo), method: :patch %>
                  </li>
                <% end %>

                <%- if admin? %>
                  <li role="menuitem">
                    <%= link_to t('.actions.destroy'), destroy_funcionario_path(vinculo.funcionario_id), class: 'edit-info',
                      data: { confirm: t('.confirmations.destroy') } %>
                  </li>
                <% end %>
              </ul>
            </td>
          </tr>
        <% end %>
      <% else %>
        <tr>
          <td colspan="7">
            Nenhum(a) funcionário(a) encontrado(a)
          </td>
        </tr>
      <% end %>
    </tbody>
</table>

<script>
  $(document).ready(function() {
    const $button = $('.dropdown-button');
    const $menu = $('.custom-dropdown-menu');

    $menu.on('mouseleave', ()=> {
      $menu.addClass('hidden')
    })

    $button.on('click', function (event) {
      const targetElement = $(event.currentTarget);

      const menu = targetElement.next();
      const expanded = targetElement.attr('aria-expanded') === 'true';

      targetElement.attr('aria-expanded', !expanded);

      menu.toggleClass('hidden');
    });
  });
</script>

app/views/funcionarios_pages/importar_funcionarios.html.erb
<h2>Importar Funcionários</h2>

<p class="description">
  Aqui você pode cadastrar funcionários por planilha em Excel. Ideal para até 500 cadastros!
</p>

<% content_for :section_navbar do %>
  <li>
    <%= link_to 'Importar Funcionários(as)', importar_funcionarios_funcionarios_pages_path %>
  </li>
<% end %>

<%= simple_form_for :employee, url: importar_funcionarios_create_funcionarios_pages_path, method: :post, html: {
  class: 'gray-form'
}, defaults: {
  wrapper_html: { class: 'default-wrapper-form' },
  input_html: { class: 'custom-input' }
} do |f| %>
  <% if consultant? || collaborator? %>
    <%= f.input :empresa_id,
        collection: @empresas,
        label: 'Empresa',
        label_method: :razao_social,
        value_method: :id,
        include_blank: true,
        input_html: {
          class: 'js-select simple-select',
          id: 'filterFormCompanyId',
          onchange: 'triggerForm()'
        },
        selected: params[:empresa_id],
        prompt: 'Selecione uma empresa',
        required: false 
      %>
    <% end %>
  <%= f.input :file, as: :file, label: 'Selecione um arquivo', input_html: { class: 'form-control' } %>
  <%= f.button :submit, "Importar", class: 'button' %>
<% end %>

app/views/funcionarios_pages/index.html.erb
<h2>Funcionários</h2>

<% content_for :section_navbar do %>
  <li class="active">
    <%= link_to 'Importar Funcionários(as)', importar_funcionarios_funcionarios_pages_path %>
  </li>
<% end %>

<p class="description">
  <% if admin? || consultant? || collaborator? %>
    Aqui você encontra todos os funcionários das empresas que você está autorizado a visualizar.
  <% else %>
    Aqui você encontra todos os funcionários da sua empresa
  <% end %>
</p>
<div class="w-full row justify-between hiddeninmodile">
  <div class="flex flex-row gap-4 max-w-screen-lg flex-wrap md:w-2/5">
    <%= form_tag funcionarios_empresa_path, method: :get, id: 'searchForm', class: 'default-search hiddeninmodile' do %>
      <%- unless employee? && !current_user.employer? %>
        <%= hidden_field_tag :role, params[:role], id: 'searchFormRole' %>
        <%= hidden_field_tag :user_status, params[:user_status], id: 'searchFormUserStatus' %>
        <%= hidden_field_tag :department, params[:department], id: 'searchFormDepartment' %>
        <%= hidden_field_tag :job_function, params[:job_function], id: 'searchFormJobFunction' %>

        <% unless employee? && current_user.employer? %>
          <%= hidden_field_tag :empresa_id, params[:empresa_id], id: 'searchFormCompanyId' %>
        <% end %>
      <% end %>

      <%= text_field_tag :query, params[:query],
                         placeholder: 'Pesquisar Funcionário(a)...' %>

      <%= button_tag class: 'icon' do %>
        <%= inline_svg 'icons/magnifier', alt: 'Buscar' %>
      <% end %>
    <% end %>
  </div>
  <div class="md:w-3/5">
    <div  class="row justify-end">
      <%= link_to 'javascript:void(0);', class:
        "open-modal filter-button
      #{(params[:role].present? || params[:user_status].present?) ? 'filtered' : ''}" do %>
        Filtrar

        <%= inline_svg 'icons/filter', alt: 'Filtrar', class: 'icon' %>
      <% end %>
    </div>
  </div>
</div>

<div class="row justify-center" style="width: 100%">
  <%= link_to 'javascript:void(0);', class:
    "open-modal filter-button blockinmodile
      #{(params[:role].present? || params[:user_status].present?) ? 'filtered' : ''}" do %>
    Filtrar

    <%= inline_svg 'icons/filter', alt: 'Filtrar', class: 'icon' %>
  <% end %>
</div>

<%= render 'filters' unless employee? && !current_user.employer? %>

<div id="funcionarios-empresa" class="table-with-scroll">
</div>

<script>
  $(function() {
    $("#searchForm, #filterForm").on("submit", function(event) {
      event.preventDefault();

      var form = $(this);

      if ($(event.target).is("#searchForm")) {
        $("#searchFormCompanyId").val($("#filterFormCompanyId").val())
        $("#searchFormRole").val($("#filterFormRole").val())
        $("#searchFormUserStatus").val($("#filterFormUserStatus").val())
        $("#searchFormDepartment").val($("#filterFormDepartment").val())
        $("#searchFormJobFunction").val($("#filterFormJobFunction").val())
      }

      $.ajax({
        url: form.attr('action'),
        method: form.attr('method'),
        data: form.serialize(),
        dataType: 'html',
        success: function(data) {
          $('#funcionarios-empresa').html(data);
        },
      });
    });

    <%- if employee? %>
      $('form').trigger('submit');
    <% end %>
  });
</script>

app/views/funcionarios_pages/new.html.erb
<%= render 'form', funcionario: @funcionario %>

<%= link_to 'Back', funcionarios_path %>

app/views/funcionarios_pages/show_lgpd.html.erb
<%= render 'shared/lgpd_terms' %>

<%= form_with url: update_lgpd_path,
  class: 'gray-form',
  method: :post do |form| %>
  <%= submit_tag 'Aceitar e continuar', class: 'button single-option' %>
<% end %>