config/routes.rb
Rails.application.routes.draw do
  # mount Rswag::Api::Engine => '/api-docs'
  # mount Rswag::Ui::Engine => '/api-docs'
  # mount ActionCable::server => '/cable'


  resources :employees, only: %i[new create], path: 'funcionarios'
  resource :two_factor_settings#, except: [:index, :show]

  # Auth
  devise_for :admin, controllers: {
    password_expired: 'funcionarios/password_expired',
    sessions: 'admin/sessions',
  }

  devise_for :empresas, controllers: {
    registrations: 'empresas/registrations',
    password_expired: 'funcionarios/password_expired',
    sessions: 'empresas/sessions',
  }

  devise_for :funcionarios, controllers: {
    omniauth_callbacks: 'funcionarios/omniauth_callbacks',
    registrations: 'funcionarios/registrations',
    sessions: 'funcionarios/sessions',
    password_expired: 'funcionarios/password_expired',
  }

  devise_for :consultants, controllers: {
    registrations: 'consultants/registrations',
    password_expired: 'funcionarios/password_expired',
    sessions: 'consultants/sessions',
  }

  devise_for :consultant_teams, controllers: {
    registrations: 'consultant_teams/registrations',
    password_expired: 'funcionarios/password_expired',
    sessions: 'consultant_teams/sessions',
  }

  # Pages
  get 'consultant', to: 'pages#consultant'
  get 'contact', to: 'pages#contact'
  root to: 'pages#home'
  get 'lgpd_text', to: 'pages#lgpd_text'

  resource :dashboard, only: :show

  # Resources
  resources :tutorials, path: 'tutoriais', only: :index

  resources :empresas_pages do
    collection do
      get :importar_funcionarios
      post :importar_funcionarios_create
    end
  end

  get 'empresas/:id/funcionarios', to: 'companies#employees', as: :company_employees

  get 'funcionarios_form/:id', to: 'empresas_pages#funcionarios_form', as: :funcionarios_form
  patch 'funcionarios_form/:id', to: 'empresas_pages#funcionarios_form_update', as: :funcionarios_form_update
  get 'funcionarios_function', to: 'empresas_pages#funcionarios_function', as: :funcionarios_function

  patch 'toggle_empregador/:id', to: 'empresas_pages#toggle_empregador', as: :toggle_empregador
  patch 'toggle_gestor/:id', to: 'empresas_pages#toggle_gestor', as: :toggle_gestor

  get 'consultants_outsourcing', to: 'consultants_pages#consultants_outsourcing', as: :consultants_outsourcing
  put 'habilitar_consultor/:consultant_id/:company_id', to: 'consultants_pages#enable_company', as: :habilitar_consultor

  resources :funcionarios_pages do
    collection do
      get :importar_funcionarios
      post :importar_funcionarios_create
    end
  end

  get 'vinculos_form/:id', to: 'funcionarios_pages#vinculos_form', as: :vinculos_form
  patch 'vinculos_form/:id', to: 'funcionarios_pages#vinculos_form_update', as: :vinculos_form_update
  patch 'desativar_vinculo', to: 'funcionarios_pages#desativar_vinculo', as: :desativar_vinculo

  get 'destroy_funcionario/:id', to: 'funcionarios_pages#destroy_funcionario', as: :destroy_funcionario

  resources :atestados

  get '/atestados_funcionario/:id', to: 'atestados#atestados_funcionario', as: :atestados_funcionario

  resources :okays, only: %i[index]

  post '/empresa_okay/:id', to: 'atestados#empresa_okay', as: :empresa_okay
  post '/funcionario_okay/:id', to: 'atestados#funcionario_okay', as: :funcionario_okay
  post '/empresa_subscrever/:id', to: 'atestados#empresa_subscrever', as: :empresa_subscrever
  post '/empresa_reverter/:id', to: 'atestados#empresa_reverter', as: :empresa_reverter

  resources :cfms, only: %i[new create]
  resources :importar_funcionarios, only: %i[index create]
  resources :bi_urls, only: %i[new create]

  get 'aceitar_lgpd', to: 'funcionarios_pages#show_lgpd'
  post 'update_lgpd', to: 'funcionarios_pages#update_lgpd'

  resources :password_resets

  get 'cid/buscar', to: 'cids#search', as: :cid_search

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :atestados, only: %i[index show]
      resources :funcionarios, only: %i[create]
      get 'opt', to: 'checks#verify_opt'
      get 'send_code', to: 'checks#send_email_with_code'
      post 'verify_code', to: 'checks#verify_code'
    end
  end

  resources :consultants, only: :index

  resources :collaborators, only: :index, path: 'colaboradores' do
    member do
      patch :authorize, path: 'autorizar'
      patch :revoke, path: 'revogar'
    end
  end

  get 'funcionarios_empresa', to: 'funcionarios_pages#funcionarios_empresa', as: 'funcionarios_empresa'

  get 'funcionarios_por_empresa/:id', to: 'atestados#funcionarios_por_empresa'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  # mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?

  resources :squads do
    collection do
      get :list
    end
  end
end

app/controllers/empresas_pages_controller.rb
class EmpresasPagesController < ApplicationController
  include AccountScope
  include BondFiltersConcern


  require_company_user! only: %i[
    index toggle_empregador
  ]

  require_consultant_user! only: %i[
    index toggle_empregador
  ]

  require_company_or_employer_role! only: %i[
    index toggle_gestor toggle_empregador
  ]

  require_collaborator_role! only: %i[
    index toggle_gestor toggle_empregador
  ]

  require_company_or_admin! only: %i[
    funcionarios_function funcionarios_form funcionarios_form_update
  ]

  before_action :authenticate_empresa!, except: %i[
    funcionarios_function funcionarios_form funcionarios_form_update toggle_gestor toggle_empregador
  ]

  layout 'redesign'

  FILTERS = {
    roles: %i[employee manager employer],
    user_statuses: %i[active inactive]
  }

  def index
    @vinculos = current_empresa.vinculos.includes(:funcionario)

    @departments = departments_for([current_empresa.id])
    @job_functions = job_functions_for([current_empresa.id])

    @vinculos = @vinculos.global_search(params[:query]) if params[:query].present?

    @vinculos = filter_by_role(@vinculos, params[:role].to_sym) if params[:role].present?

    @vinculos = filter_by_status(@vinculos, params[:user_status].to_sym) if params[:user_status].present?
    @vinculos = filter_by_department(@vinculos, params[:department]) if params[:department].present?
    @vinculos = filter_by_job_function(@vinculos, params[:job_function]) if params[:job_function].present?

    @vinculos = filter_by_employee_leader(@vinculos, params[:funcionario_lider_id]) if params[:funcionario_lider_id].present?

    @vinculos = @vinculos.left_joins(:refatestados)
                             .group(:id)
                             .reorder('COUNT("atestados"."id") DESC')
  end

  def toggle_empregador
    if admin? || consultant? || collaborator? 
      bond = Vinculo.find(params[:id])
    else
      bond = current_user.vinculos.find_by_id(params[:id])
    end
   
    return render_not_found_page unless bond

    message = t('.error')
    message = t('.success') if bond.update(empregador: !!!bond.empregador?)

    if company?
      redirect_to empresas_pages_path, notice: message
    else
      redirect_to funcionarios_pages_path, notice: message
    end
  end

  def toggle_gestor
    destination = empresas_pages_path

    if admin? || consultant? || collaborator?
      bond = Vinculo.find(params[:id])
    elsif company?
      bond = current_user.vinculos.find_by_id(params[:id])
    elsif employee? && current_user.employer?
      destination = funcionarios_pages_path

      employer_bond = current_user.most_recent_bond

      bond = Vinculo.where(empresa_id: employer_bond.empresa_id)
                    .find_by_id(params[:id])
    end

    if consultant? || collaborator?
      destination = funcionarios_pages_path
    end

    return render_not_found_page unless bond

    message = t('.error')

    message = t('.success') if bond.update(gestor: !!!bond.gestor?)

    redirect_to destination, notice: message
  end

  def funcionarios_function
    if admin?
      @company_id = params.fetch('/funcionarios_function', {}).fetch(:company_id, nil)

      if @company_id
        source = Vinculo.where(empresa_id: @company_id)
      else
        source = Vinculo.where(empresa_id: -1)
      end
    else
      source = current_empresa.vinculos
    end

    employee_ids = source.where(empregador: true).ids
    manager_ids = source.where(gestor: true).ids

    @vinculos = Vinculo.where(id: employee_ids.concat(manager_ids))
  end

  def funcionarios_form
    if admin?
      @vinculo = Vinculo.find(params[:id])
    else
      @vinculo = current_user.vinculos.find_by_id(params[:id])
    end

    return render_not_found_page unless @vinculo
  end

  def funcionarios_form_update
    if admin?
      bond = Vinculo.find(params[:id])
    else
      bond = current_user.vinculos.find_by_id(params[:id])
    end

    return render_not_found_page unless bond

    employee = bond.funcionario

    message = t('.error')

    message = t('.success') if employee.update(funcionario_params)

    redirect_to empresas_pages_path, notice: message
  end


  def importar_funcionarios
  end

  def importar_funcionarios_create
    return redirect_to empresas_pages_path if params[:employee].nil?

    xlsx = Roo::Spreadsheet.open(params[:employee][:file].tempfile)

    xlsx.each_with_index do |row, index|
      next if index.zero?
      
      begin
        password = SecureRandom.hex(10)
        funcionario = Funcionario.find_or_create_by(cpf: row[1])
        
        funcionario.update({
          nome: row[0],
          rg: row[2],
          data_nascimento: row[3].strftime('%d/%m/%Y'),
          sexo: row[4],
          celular: row[5],
          email: row[6],
          registro_empresa: row[10],
          pis: row[11],
          risco_ocupacional: row[12],
          password: password,
          password_confirmation: password
        })

        squad = Squad.find_or_create_by(
          name: row[8], 
          empresa: current_empresa 
        )

        vinculo = Vinculo.find_or_create_by(
          empresa_id: current_empresa.id,
          funcionario_id: funcionario.id,
        )
        vinculo.update({
          empregador: false,
          cargo:  row[7],
          squad: squad,
          aprovado: false,
          cnpj_employee:  row[9],
          ativo: (row[13].to_s.downcase == "ativo")? true: false
        })

      rescue
      end
    end

    redirect_to empresas_pages_path, notice: "Processamos o arquivo com sucesso!"
  end

  private

  def empresa_params
    params.require(:empresa).permit(
      :razao_social, :cnpj, :telefone,
      :celular, :email, :endereco,
      :estado, :cidade, :cep, :contato, :cargo
    )
  end

  def funcionario_params
    params.require(:funcionario).permit(
      :nome,
      :registro_empresa, :pis, :risco_ocupacional,
      vinculos_attributes: %i[
        id cargo cnpj_employee squad_id funcionario_lider_id ativo
      ]
    )
  end

  def filter_by_role(bonds, role)
    return bonds if bonds.empty? || !FILTERS[:roles].include?(role)

    case role
    when :employee
      bonds.where(empregador: false, gestor: false)
    when :manager
      bonds.where(empregador: false, gestor: true)
    when :employer
      bonds.where(empregador: true, gestor: false)
    else
      bonds
    end
  end

  def filter_by_status(bonds, status)
    return bonds if bonds.empty? || !FILTERS[:user_statuses].include?(status.to_sym)

    filtered_bonds = bonds.joins('INNER JOIN funcionarios AS func ON vinculos.funcionario_id = func.id')

    case status.to_sym
    when :active
      filtered_bonds.where('vinculos.ativo = true')
    when :inactive
      filtered_bonds.where('vinculos.ativo = false')
    else
      filtered_bonds
    end
  end

end

app/views/empresas_pages/_filters.html.erb
<%= render 'redesign/shared/modal' do %>
  <h3>Filtros</h3>

  <%= simple_form_for('', url: empresas_pages_path, method: :get,
    html: { class: 'gray-form' },
    defaults: {
      wrapper_html: { class: 'default-wrapper-form' },
      input_html: { class: 'custom-input' }
    }) do |f| %>

    <%= f.input :query, as: :hidden, input_html: { value: params[:query] } %>

    <div class="flex flex-col gap-4">
      <%= f.input :role,
        collection: [
          ['Empregador', 'employer'],
          ['Gestor', 'manager'],
          ['Funcionário', 'employee']
        ],
        selected: params[:role],
        prompt: 'Selecione um perfil',
        input_html: { class: 'js-select' },
        include_blank: true,
        required: false %>

      <%= f.input :user_status,
        collection: [
          ['Ativo', 'active'],
          ['Inativo', 'inactive']
        ],
        selected: params[:user_status],
        prompt: 'Selecione um status',
        input_html: { class: 'js-select' },
        include_blank: true,
        required: false %>

      <%= f.input :department,
        collection: @departments,
        selected: params[:department],
        prompt: 'Selecione o Departamento',
        input_html: { class: 'js-select' },
        include_blank: true,
        required: false %>

      <%= f.input :job_function,
        collection: @job_functions,
        selected: params[:job_function],
        prompt: 'Selecione o Cargo',
        input_html: { class: 'js-select' },
        include_blank: true,
        required: false %>

      <%= f.input :funcionario_lider_id,
          collection: lideres_by_empresa,
          selected: params[:funcionario_lider_id],
          prompt: 'Selecione o Lider Direto',
          input_html: { class: 'js-select' },
          include_blank: true,
          required: false %>

      <div class="filters-form">
        <div class="flex flex-row flex-wrap gap-4 mt-4">
          <%= link_to 'Limpar Filtros', empresas_pages_path, class: 'clear-filters-button' %>

          <%= f.button :submit, 'Filtrar', class: 'button' %>
        </div>
      </div>
    </div>
  <% end %>
<% end %>

app/views/empresas_pages/funcionarios_form.html.erb
<h2>
  Editar Informações
</h2>

<%= simple_form_for(@vinculo.funcionario, url: funcionarios_form_update_path(@vinculo.id), html: {
  class: 'gray-form'
}, defaults: {
  wrapper_html: { class: 'default-wrapper-form' },
  input_html: { class: 'custom-input' }
}) do |f| %>
  <%= f.error_notification %>
  <%= f.input :nome, autofocus: true, label: 'Nome do Funcionário', readonly: !company? &&  !can_do? %>

  <%= f.input :cpf, autofocus: true, label: 'CPF', hint: '*somente leitura', readonly: true %>

  <%= f.input :rg, label: 'RG', hint: '*somente leitura', readonly: true %>

  <%= f.input :sexo, autofocus: true, label: 'Gênero', hint: '*somente leitura', readonly: true %>

  <%= f.input :data_nascimento, label: 'Data de Nascimento', hint: '*somente leitura', readonly: true %>

  <%= f.input :pis, autofocus: true, label: 'PIS', hint: '*Número do PIS' %>

  <%= f.input :celular, autofocus: true, label: 'Celular', hint: '*somente leitura', readonly: true %>

  <%= f.input :email, label: 'Email', hint: '*somente leitura', readonly: true %>

  <%= f.input :registro_empresa, autofocus: true, label: 'Registro na Empresa', hint: '*Número de matrícula' %>

  <%= f.simple_fields_for :vinculos do |v| %>
    <% if v.object.id == @vinculo.id %>
      <%= v.input :id, as: :hidden, input_html: { value: v.object.id } %>

      <%= v.input :ativo, collection: [['Sim', true], ['Não', false]], hint: 'Situação do usuário', label: 'Ativo', include_blank: true, readonly: has_role_permission? %>

      <%= v.input :squad_id, collection: squads_by_empresa, hint: 'Informe um novo departamento', label: 'Departamento', include_blank: true,  readonly: !has_role_permission? %>

      <%= v.input :cargo, hint: 'Informe a nova função', include_blank: true, readonly: !has_role_permission? %>

      <%= v.input :funcionario_lider_id, collection: lideres_by_empresa(@vinculo.funcionario.id), hint: 'Informe o líder direto', label: 'Líder direto', include_blank: 'Admin-empresa', readonly: !has_role_permission?  %>

      <%= v.input :cnpj_employee, autofocus: true, label: 'CNPJ do Funcionário', hint: 'CNPJ alocado na Empresa', include_blank: true, readonly: !has_role_permission?%>
    <% end %>
  <% end %>

  <%= f.input :risco_ocupacional, autofocus: true, label: 'Risco Ocupacional' %>

  <%= f.button :submit, 'Atualizar', class: 'button' %>
<% end %>

app/views/empresas_pages/funcionarios_function.html.erb
<h2>Controle de Funções</h2>

<p class="description">
  <% if admin? %>
    Aqui você pode consultar as funções dos funcionários das empresas.
  <% else %>
    Aqui você pode consultar as funções dos funcionários da sua empresa.
  <% end %>
</p>

<% if admin? %>
  <%= simple_form_for funcionarios_function_path, method: :get,
    defaults: {
      wrapper_html: { class: 'default-wrapper-form' },
      input_html: { class: 'custom-input' }
    },
    html: {
      id: 'employee_function_form',
      class: 'default-search',
      autocomplete: 'off'
    } do |f| %>
    <%= f.input :company_id,
      label: false,
      prompt: 'Selecione a empresa',
      selected: @company_id,
      input_html: { class: 'js-select w-full' },
      collection: Empresa.all.map {
        |company| [company.razao_social, company.id]
      }, include_blank: true %>

    <%= button_tag class: 'icon' do %>
      <%= inline_svg 'icons/magnifier', alt: 'Buscar' %>
    <% end%>
  <% end %>
<% end %>

<div class="table-with-scroll">
  <table class="custom-table">
    <thead>
      <tr>
        <th scope="col" class="text-center">
          Nome
        </th>

        <th scope="col" class="text-center">
          Celular
        </th>

        <th scope="col" class="text-center hidden md:table-cell">
          Departamento
        </th>

        <th scope="col" class="text-center">
          Cargo
        </th>

        <th scope="col" class="text-center">
          Empregador
        </th>

        <th scope="col" class="text-center">
          Gestor
        </th>
      </tr>
    </thead>

    <tbody>
      <% @vinculos.each do |vinculo| %>
        <tr>
          <td class="text-left"><%= vinculo.funcionario.nome %></td>
          <td class="text-center"><%= vinculo.funcionario.celular %></td>
          <td class="text-center hidden md:table-cell"><%= vinculo.squad %></td>
          <td class="text-center"><%= vinculo.cargo %></td>

          <td class="text-center">
            <%- if vinculo.empregador %>
              <%= inline_svg 'icons/check', class: 'mx-auto w-6' %>
            <% else %>
              <%= inline_svg 'icons/x', class: 'mx-auto w-7' %>
            <% end %>
          </td>

          <td class="text-center">
            <%- if vinculo.gestor %>
              <%= inline_svg 'icons/check', class: 'mx-auto w-6' %>
            <% else %>
              <%= inline_svg 'icons/x', class: 'mx-auto w-7' %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/empresas_pages/importar_funcionarios.html.erb
<h2>Importar Funcionários</h2>

<p class="description">
  Aqui você pode cadastrar funcionários por planilha em Excel. Ideal para até 500 cadastros!
</p>

<% content_for :section_navbar do %>
  <li>
    <%= link_to 'Funcionários', empresas_pages_path %>
  </li>

  <li>
    <%= link_to 'Cadastro de Funcionário', new_employee_path %>
  </li>
  
  <li class="active">
    <%= link_to 'Importar Funcionários(as)', importar_funcionarios_empresas_pages_path %>
  </li>
<% end %>

<%= simple_form_for :employee, url: importar_funcionarios_create_empresas_pages_path, method: :post, html: {
  class: 'gray-form'
}, defaults: {
  wrapper_html: { class: 'default-wrapper-form' },
  input_html: { class: 'custom-input' }
} do |f| %>
  <%= f.input :file, as: :file, label: 'Selecione um arquivo', input_html: { class: 'form-control' } %>
  <%= f.button :submit, "Importar", class: 'button' %>
<% end %>

app/views/empresas_pages/index.html.erb
<h2>Funcionários</h2>

<p class="description">
  Aqui você encontra todos os funcionários da sua empresa
</p>

<% content_for :section_navbar do %>
  <li class="active">
    <%= link_to 'Funcionários', empresas_pages_path %>
  </li>

  <li>
    <%= link_to 'Cadastro de Funcionário', new_employee_path %>
  </li>

  <li>
    <%= link_to 'Importar Funcionários(as)', importar_funcionarios_empresas_pages_path %>
  </li>
<% end %>

<div class="flex flex-row gap-4 max-w-screen-lg flex-wrap hiddeninmodile">
  <%= form_tag empresas_pages_path, method: :get, class: 'default-search ' do %>
    <%= hidden_field_tag :role, params[:role] %>
    <%= hidden_field_tag :user_status, params[:user_status] %>
    <%= hidden_field_tag :department, params[:department] %>
    <%= hidden_field_tag :job_function, params[:job_function] %>

    <%= text_field_tag :query, params[:query],
      placeholder: 'Pesquisar Funcionário(a)...' %>

    <%= button_tag class: 'icon' do %>
      <%= inline_svg 'icons/magnifier', alt: 'Buscar' %>
    <% end %>
  <% end %>

  <%= link_to 'javascript:void(0);', class: "open-modal filter-button #{(params[:role].present? || params[:user_status].present?) ? 'filtered' : ''}" do %>
    Filtrar

    <%= inline_svg 'icons/filter', alt: 'Filtrar', class: 'icon' %>
  <% end %>

</div>

<div class="row justify-center w-full blockinmodile">
  <%= link_to 'javascript:void(0);', class: "open-modal filter-button #{(params[:role].present? || params[:user_status].present?) ? 'filtered' : ''}" do %>
    Filtrar

    <%= inline_svg 'icons/filter', alt: 'Filtrar', class: 'icon' %>
  <% end %>
</div>


<%= render 'filters' %>
<% if @vinculos.length > 0 %>
  <h3 class="text-lg mt-5 mb-3">
    Total de Funcionários: <%= @vinculos.length %>
  </h3>
<% end %>

<div class="table-with-scroll">
  <table class="custom-table">
    <thead>
      <tr>
        <th role="col" class="text-center">Nome</th>
        <th role="col" class="hidden md:table-cell text-center">E-mail</th>
        <th role="col" class="hidden md:table-cell text-center">Departamento</th>
        <th role="col" class="text-center">Cargo</th>
        <th role="col" class="hidden md:table-cell text-center">Líder Direto</th>
        <th role="col" class="hidden md:table-cell text-center">Status Usuário</th>
        <th role="col" class="hidden md:table-cell text-center">Perfil</th>
        <th role="col" class="text-center">Qtd. Atestados</th>
        <th role="col" class="text-center">Ações</th>
      </tr>
    </thead>
    <tbody>

      <% if @vinculos.length > 0 %>

        <% @vinculos.each do |vinculo| %>
          <tr>
            <td>
              <%= vinculo.funcionario.nome %>
            </td>

            <td class="hidden md:table-cell">
              <%= vinculo.funcionario.email %>
            </td>

            <td class="hidden md:table-cell">
              <%= vinculo.squad %>
            </td>

            <td class="text-center">
              <%= vinculo.cargo %>
            </td>

            <td class="hidden md:table-cell">
              <%= vinculo.nome_lider %>
            </td>

            <td class="hidden md:table-cell">
              <% if vinculo.ativo %>
                <span class="tag active">Ativo</span>
              <% else %>
                <span class="tag deactivated">Inativo</span>
              <% end %>
            </td>

            <td class="text-center hidden md:table-cell">
              <%= t(role_by_bound(vinculo), scope: 'empresas_pages.index.roles') %>
            </td>

            <td class="text-center">
              <div class="flex items-center justify-center">
                <%= vinculo.refatestados.where(empresa_id: current_user.empresa.id).count  %>
                <%= inline_svg 'icons/alert', style: "width: 20px; height: 20px; margin-left: 10px" if vinculo.sum_tempo_de_dispensa_em_horas_per_funcionario? %>
              </div>
            </td>

            <td class="relative">
              <button aria-haspopup="true" aria-expanded="false" class="action dropdown-button">
                <%= inline_svg 'icons/ellipsis', alt: 'Ações', class: 'mx-auto' %>
              </button>

              <ul class="custom-dropdown-menu hidden" aria-labelledby="dropdown-button" role="menu">
                <% if company? %>
                  <li role="menuitem">
                    <%= link_to "#{vinculo.empregador ? 'Remover empregador' : 'Adicionar empregador'}", toggle_empregador_path(vinculo), method: :patch %>
                  </li>

                  <li role="menuitem">
                    <%= link_to "#{vinculo.gestor ? 'Remover gestor' : 'Adicionar gestor'}", toggle_gestor_path(vinculo), method: :patch %>
                  </li>
                <% end %>

                <li role="menuitem">
                  <%= link_to t('.actions.edit'), funcionarios_form_path(vinculo.id) %>
                </li>

                <li role="menuitem">
                  <%= link_to 'Detalhes', atestados_funcionario_path(vinculo.funcionario) %>
                </li>
              </ul>
            </td>
          </tr>
        <% end %>
      <% else %>
        <tr>
          <td colspan="3" class="table-cell md:hidden text-center">
            Nenhum(a) funcionário(a) encontrado(a).
          </td>

          <td colspan="7" class="hidden md:table-cell text-center">
            Nenhum(a) funcionário(a) encontrado(a).
          </td>
      <% end %>
    </tbody>
  </table>
</div>

<script>
  $(document).ready(function() {
    const $button = $('.dropdown-button');
    const $menu = $('.custom-dropdown-menu');

    $menu.on('mouseleave', ()=> {
        $menu.addClass('hidden')
    })

    $button.on('click', function (event) {
      const targetElement = $(event.currentTarget);

      const menu = targetElement.next();
      const expanded = targetElement.attr('aria-expanded') === 'true';

      targetElement.attr('aria-expanded', !expanded);

      menu.toggleClass('hidden');
    });
  });
</script>

app/views/empresas_pages/new.html.erb
<%= render 'form', empresa: @empresa %>

<%= link_to 'Back', empresas_path %>