config/routes.rb
Rails.application.routes.draw do
  # mount Rswag::Api::Engine => '/api-docs'
  # mount Rswag::Ui::Engine => '/api-docs'
  # mount ActionCable::server => '/cable'


  resources :employees, only: %i[new create], path: 'funcionarios'
  resource :two_factor_settings#, except: [:index, :show]

  # Auth
  devise_for :admin, controllers: {
    password_expired: 'funcionarios/password_expired',
    sessions: 'admin/sessions',
  }

  devise_for :empresas, controllers: {
    registrations: 'empresas/registrations',
    password_expired: 'funcionarios/password_expired',
    sessions: 'empresas/sessions',
  }

  devise_for :funcionarios, controllers: {
    omniauth_callbacks: 'funcionarios/omniauth_callbacks',
    registrations: 'funcionarios/registrations',
    sessions: 'funcionarios/sessions',
    password_expired: 'funcionarios/password_expired',
  }

  devise_for :consultants, controllers: {
    registrations: 'consultants/registrations',
    password_expired: 'funcionarios/password_expired',
    sessions: 'consultants/sessions',
  }

  devise_for :consultant_teams, controllers: {
    registrations: 'consultant_teams/registrations',
    password_expired: 'funcionarios/password_expired',
    sessions: 'consultant_teams/sessions',
  }

  # Pages
  get 'consultant', to: 'pages#consultant'
  get 'contact', to: 'pages#contact'
  root to: 'pages#home'
  get 'lgpd_text', to: 'pages#lgpd_text'

  resource :dashboard, only: :show

  # Resources
  resources :tutorials, path: 'tutoriais', only: :index

  resources :empresas_pages do
    collection do
      get :importar_funcionarios
      post :importar_funcionarios_create
    end
  end

  get 'empresas/:id/funcionarios', to: 'companies#employees', as: :company_employees

  get 'funcionarios_form/:id', to: 'empresas_pages#funcionarios_form', as: :funcionarios_form
  patch 'funcionarios_form/:id', to: 'empresas_pages#funcionarios_form_update', as: :funcionarios_form_update
  get 'funcionarios_function', to: 'empresas_pages#funcionarios_function', as: :funcionarios_function

  patch 'toggle_empregador/:id', to: 'empresas_pages#toggle_empregador', as: :toggle_empregador
  patch 'toggle_gestor/:id', to: 'empresas_pages#toggle_gestor', as: :toggle_gestor

  get 'consultants_outsourcing', to: 'consultants_pages#consultants_outsourcing', as: :consultants_outsourcing
  put 'habilitar_consultor/:consultant_id/:company_id', to: 'consultants_pages#enable_company', as: :habilitar_consultor

  resources :funcionarios_pages do
    collection do
      get :importar_funcionarios
      post :importar_funcionarios_create
    end
  end

  get 'vinculos_form/:id', to: 'funcionarios_pages#vinculos_form', as: :vinculos_form
  patch 'vinculos_form/:id', to: 'funcionarios_pages#vinculos_form_update', as: :vinculos_form_update
  patch 'desativar_vinculo', to: 'funcionarios_pages#desativar_vinculo', as: :desativar_vinculo

  get 'destroy_funcionario/:id', to: 'funcionarios_pages#destroy_funcionario', as: :destroy_funcionario

  resources :atestados

  get '/atestados_funcionario/:id', to: 'atestados#atestados_funcionario', as: :atestados_funcionario

  resources :okays, only: %i[index]

  post '/empresa_okay/:id', to: 'atestados#empresa_okay', as: :empresa_okay
  post '/funcionario_okay/:id', to: 'atestados#funcionario_okay', as: :funcionario_okay
  post '/empresa_subscrever/:id', to: 'atestados#empresa_subscrever', as: :empresa_subscrever
  post '/empresa_reverter/:id', to: 'atestados#empresa_reverter', as: :empresa_reverter

  resources :cfms, only: %i[new create]
  resources :importar_funcionarios, only: %i[index create]
  resources :bi_urls, only: %i[new create]

  get 'aceitar_lgpd', to: 'funcionarios_pages#show_lgpd'
  post 'update_lgpd', to: 'funcionarios_pages#update_lgpd'

  resources :password_resets

  get 'cid/buscar', to: 'cids#search', as: :cid_search

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :atestados, only: %i[index show]
      resources :funcionarios, only: %i[create]
      get 'opt', to: 'checks#verify_opt'
      get 'send_code', to: 'checks#send_email_with_code'
      post 'verify_code', to: 'checks#verify_code'
    end
  end

  resources :consultants, only: :index

  resources :collaborators, only: :index, path: 'colaboradores' do
    member do
      patch :authorize, path: 'autorizar'
      patch :revoke, path: 'revogar'
    end
  end

  get 'funcionarios_empresa', to: 'funcionarios_pages#funcionarios_empresa', as: 'funcionarios_empresa'

  get 'funcionarios_por_empresa/:id', to: 'atestados#funcionarios_por_empresa'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  # mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?

  resources :squads do
    collection do
      get :list
    end
  end
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible " role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible " role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer-distributed">
  <div class="footer-left">
    <div id="footer-logo-img">
      <%= image_tag 'logos/siklee_small.png' %>
    </div>

    <p class="footer-links">
    <a href="#" class="link-1">Home</a>
    </p>
    <p class="footer-links">
    <a href="/api-docs" target="_blank" class="link-1">API Docs</a>
    </p>
  </div>

  <div class="footer-center">

    <div class="footer-element">
      <i class="fa fa-phone icon-footer" aria-hidden="false"></i>
      <p>+55 (11) 99994-9304</p>
    </div>

    <div class="footer-element">
      <i class="fa fa-envelope"></i>
      <p><a href="mailto:leonardo@siklee.com">leonardo@siklee.com</a></p>
    </div>
  </div>

  <div class="footer-right">
    <p class="footer-company-about small-text">
    <span class="small-title">A Empresa</span>
    Startup que ajuda as empresas na gestão dos atestados e faltas dos colaboradores(as) no trabalho.
    </p>
    <div class="footer-icons">
    </div>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<div class="navbar fixed-top navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "/", class: "navbar-brand" do %>
    <% if current_empresa&.logo.presence %>
      <%= image_tag current_empresa.logo, class: "nav-logo" %>
    <% elsif current_funcionario&.vinculos&.joins(:empresa)&.first&.empresa&.logo.presence %>
      <%= image_tag current_funcionario.vinculos.first.empresa.logo, class: "nav-logo" %>
    <% elsif !current_funcionario.nil? && current_app&.logo %>
      <%= image_tag current_app.logo, class: "nav-logo" %>
    <% elsif current_funcionario.nil? && current_app&.consultants&.first&.logo&.attached? %>
      <%= image_tag current_app.consultants.first.logo, class: "nav-logo" %>
    <% elsif current_user %>
      <%= image_tag 'logos/siklee_small.png', class: 'nav-logo' %>
    <% else %>
      <%= image_tag 'logos/siklee_medium.png', class: 'landing-page-logo' %>
    <% end %>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if admin_signed_in? %>
        <%= render 'shared/menu/admin' %>
      <% elsif current_funcionario %>
        <% if current_funcionario.vinculos.last.empregador? %>
          <%= render 'shared/menu/employee_employer' %>
        <% elsif current_funcionario.vinculos.last.gestor? %>
          <%= render 'shared/menu/employee_manager' %>
        <% else %>
          <%= render 'shared/menu/employee' %>
        <% end %>
      <% elsif current_empresa %>
        <%= render 'shared/menu/company' %>
      <% elsif current_consultant %>
        <%= render 'shared/menu/consultant' %>
      <% elsif current_consultant_team %>
        <%= render 'shared/menu/consultant_team' %>
      <% else %>
        <li class="nav-item">
          <%= link_to 'Acessar a plataforma', new_empresa_session_path, class: 'link login-page-link' %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_profile.html.erb
<% if admin? %>
  <h4 class="profile-subtitle"><%= current_admin.email %></h3>

  <div class="profile-info"></div>
<% elsif company? %>
    <%= profile_photo_for(current_empresa) %>

    <h4 class="profile-name"><%= current_empresa.razao_social %></h4>
    <h4 class="profile-subtitle"><%= current_empresa.email %></h4>
    <h4 class="profile-subtitle"><%= current_empresa.celular %></h4>

    <div class="profile-info">
      <%= link_to "Editar Informações", edit_empresa_registration_path, class: "edit-info" %>
    </div>
<% elsif employee? %>
  <%= profile_photo_for(current_funcionario) %>

  <h4 class="profile-name"><%= current_funcionario.nome %></h4>
  <h4 class="profile-subtitle"><%= current_funcionario.vinculos.last.empresa.razao_social %></h4>
  <h4 class="profile-subtitle"><%= current_funcionario.email %></h4>
  <h4 class="profile-subtitle"><%= current_funcionario.celular %></h4>

  <div class="profile-info">
    <%= link_to "Editar Informações", edit_funcionario_registration_path, class: "edit-info" %>
  </div>
<% elsif consultant? %>
  <%= profile_photo_for(current_consultant) %>

  <h4 class="profile-name"><%= current_consultant.nome %></h4>
  <h4 class="profile-subtitle"><%= current_consultant.email %></h4>
  <h4 class="profile-subtitle"><%= current_consultant.celular %></h4>

  <div class="profile-info">
    <%= link_to "Editar Informações", edit_consultant_registration_path, class: "edit-info" %>
  </div>

<% elsif collaborator? %>
  <%= profile_photo_for(current_consultant_team) %>

  <h4 class="profile-name"><%= current_consultant_team.nome %></h4>
  <h4 class="profile-subtitle"><%= current_consultant_team.email %></h4>
  <h4 class="profile-subtitle"><%= current_consultant_team.celular %></h4>

  <div class="profile-info">
    <%= link_to "Editar Informações", edit_consultant_team_registration_path, class: "edit-info" %>
  </div>
<% end %>

<%= content_for(:profile_additional_info) %>